### ISSUE TITLE
how to fix this error?

### ISSUE THREAD

**Issue by csantanaes** [adriaan90/Facebook-web-scraper#1]
File "C:/Users/user_meu/AppData/Roaming/JetBrains/PyCharmCE2020.1/scratches/oi.py", line 188, in json_to_obj
    with open(filename) as json_file:
FileNotFoundError: [Errno 2] No such file or directory: 'credentials.json'

Process finished with exit code 1

**Comment by adriaan90** [comment]
This error is generated from a file in your PyCharm scratches folder `oi.py`. You can read about the scratches folder in PyCharm [here](https://www.jetbrains.com/help/pycharm/scratches.html). Do you get this error when you try to run one of the Facebook web scrapers?

**Comment by adriaan90** [comment]
No reponse from @csantanaes . Closing issue.
