### ISSUE TITLE
I'm getting this issue;

### ISSUE THREAD

**Issue by fsiddh** [adriaan90/Facebook-web-scraper#2]
![Capture](https://user-images.githubusercontent.com/56497318/89054142-f8619300-d375-11ea-80ec-5ceb5096493d.PNG)
![c1](https://user-images.githubusercontent.com/56497318/89054211-13cc9e00-d376-11ea-91f1-7169c7927b88.PNG)

**Comment by adriaan90** [comment]
It looks like you tried to access a webpage in Facebook that you do not have access to like a private group? This resulted in your variable `eligible` to be empty and the `random` function cannot operate on an empty list.

**Comment by fsiddh** [comment]
ohh 
okay. I'll try once again
