### ISSUE TITLE
Not Working For Another Post Ids

### ISSUE THREAD

**Issue by AadarshGupta222** [adriaan90/Facebook-web-scraper#3]
The **Scraper** is only working for some **particular** post ids like the one you had provided. but for **new post** ids, it is **returning** the content of the **post** in an **Encoded Forma**t.

**Comment by adriaan90** [comment]
Hi Aadarsh

Apologies for replying to this issue only now. Since you raised the issue, other issues emerged, so I am going to overhaul the code a bit. Hopefully the refreshed code will be able to handle any post ID.
