### ISSUE TITLE
I can't get likes

### ISSUE THREAD

**Issue by MohamedSELAMA** [adriaan90/Facebook-web-scraper#5]
Hi,

when i run the likes function, i cant redirect to this always the soup in the login page

how i can fix this please.

Regards,

**Comment by adriaan90** [comment]
Hi Mohamed

Thanks for highlighting the issue. It seems like using `requests` to log into Facebook is not working anymore. I have tried some additional steps to see if I can get it to log in using `requests`, but I was not successful. 

I am going to change the code to use a Selenium headless browser to log into Facebook as it is a bit simpler compared to `requests`.

**Comment by C0DE33301** [comment]
I tried creating a Facebook account with python selenium. I get disabled immediately. Even I used User-Agent that don't help. Not sure if you login in with your regular account you may get disabled immediately?

**Comment by adriaan90** [comment]
Thanks for the heads-up. That will be really unfortunate if Selenium cannot be used either? Any other suggestions, apart from using Facebook's API?
